ramips: update Bolt BL201 to match stock bootloader
coolsnowwolf/lede pull request #12361
Opened 2024-07-25 10:21 UTC by yhpgi

There is no need to change the bootloader using Breedweb anymore. But breedweb can still be used.

Changes:
1. Update device baudrate
2. Update some of the LEDs and button GPIOs values and names
3. Update the partition layout to match the stock layout
4. Update the missing package for USB
5. Add device UIMAGE Magic value
6. Update switch layout

Test: PASS

2024-07-25 12:01 UTC, aiamadeus requested changes

2024-07-25 12:01 UTC, aiamadeus commented on target/linux/ramips/dts/mt7620a_bolt_bl201.dts
> +	nvmem-cells = <&macaddr_factory_28 0>;
kernel 5.4: mtd-mac-address

2024-07-25 12:01 UTC, aiamadeus commented on target/linux/ramips/dts/mt7620a_bolt_bl201.dts
> +	nvmem-cells = <&eeprom_factory_0>;
current driver version unsupported

2024-07-25 12:01 UTC, aiamadeus commented on target/linux/ramips/dts/mt7620a_bolt_bl201.dts
> +		nvmem-cells = <&eeprom_factory_8000>;
current driver version unsupported

2024-07-25 12:01 UTC, aiamadeus commented on target/linux/ramips/dts/mt7620a_bolt_bl201.dts
> +	compatible = "fixed-layout";
unsupported in kernel 5.4

2024-07-25 13:14 UTC, yhpgi commented
Test Result: OK

2024-07-25 13:30 UTC, yhpgi commented on target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
> +	ucidef_set_led_default "power" "power" "blue:power" "1"
I have no clue why it's not enabled by default even though I set it on the DTS.
that's why I added this workaround to make sure the power LED is turned on.
do you have a better solution?

2024-07-26 02:09 UTC, aiamadeus commented on target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
> +	ucidef_set_led_default "power" "power" "blue:power" "1"
```
		led_power: led-power {
			label = "blue:power";
			gpios = <&gpio1 9 GPIO_ACTIVE_LOW>;
			default-state = "on";
		};
```

2024-07-26 07:28 UTC, yhpgi commented on target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
> +	ucidef_set_led_default "power" "power" "blue:power" "1"
> ```
> 			default-state = "on";
> ```

This actually makes the LED keep turned on when it's booting and upgrading.
I found that removing `#include <dt-bindings/leds/common.h>` and using LED `label` fixed the problem.

2024-07-27 10:01 UTC, merged