v2ray 4.28.2
coolsnowwolf/lede pull request #5508
Opened 2020-09-21 10:02 UTC by 819-dev

v2ray同步至4.28.2

Q：你知道这是`pull request`吗？(使用 "x" 选择)
* [x ] 我知道

2020-09-21 10:38 UTC, liyufan requested changes

2020-09-21 10:38 UTC, liyufan commented on package/lean/v2ray/Makefile
> +PKG_HASH:=e5d6603454622e1f466c4c20061992046124fc7c
应为`e78446333fd28ef8a3ec2c25612458bfc024a226008888ed5277201136f4ca97`

2020-09-21 10:44 UTC, liyufan commented on package/lean/v2ray/Makefile
> +PKG_HASH:=e5d6603454622e1f466c4c20061992046124fc7c
是`PKG_HASH`而不是`PKG_SOURCE_VERSION`

2020-09-21 11:06 UTC, Myoko commented on package/lean/v2ray/Makefile
> +PKG_HASH:=e5d6603454622e1f466c4c20061992046124fc7c
已经pull过了！大雕说 兼容性问题 再等等

2020-09-22 01:31 UTC, minlang112 commented
v2ray新版需要和服务器端版本一致！

2020-09-22 10:12 UTC, Myoko commented
> v2ray新版需要和服务器端版本一致！

那也不一定！我的客户端和服务端的版本不一致也正常使用！没出问题

2020-09-23 06:38 UTC, merged

2020-09-23 09:05 UTC, OleStore commented on package/lean/v2ray/Makefile
> +PKG_HASH:=e5d6603454622e1f466c4c20061992046124fc7c
e78446333fd28ef8a3ec2c25612458bfc024a226008888ed5277201136f4ca97 难道不是这个？？