添加mvebu的支持，例如wrt3200
coolsnowwolf/lede pull request #5767
Opened 2020-11-09 16:32 UTC by 4860575

Q：你知道这是`pull request`吗？(使用 "x" 选择)
* [ x] 我知道

2020-11-11 02:50 UTC, AmadeusGhost requested changes

2020-11-11 02:50 UTC, AmadeusGhost commented on package/lean/autocore/files/arm/index.htm
> + 		<legend><%:Associated Stations%></legend>
这里加这个干啥？

2020-11-11 02:50 UTC, AmadeusGhost commented on package/lean/autocore/files/arm/sbin/cpuinfo
> +	cpu_freq="$(cat "/proc/cpuinfo" | grep "BogoMIPS" | sed -n "1p" | awk -F ': ' '{print $2}') MHz"
建议将这一行改到上面，不然 bcm53xx 的就被覆盖掉了，`sys_temp` 上面已经有了，不用重复写，而且同样也把上面的 ipq40xx 覆盖掉了，个人觉得这个文件改这里就行：
```
if grep -q "bcm53xx" "/etc/openwrt_release"; then
	cpu_freq="$(nvram get clkfreq | awk -F ',' '{print $1}')MHz"
elif grep -q "mvebu" "/etc/openwrt_release"; then
	cpu_freq="$(cat "/proc/cpuinfo" | grep "BogoMIPS" | sed -n "1p" | awk -F ': ' '{print $2}')MHz"
else
	cpu_freq="$(expr $(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq) / 1000)MHz"
fi
```

2020-11-11 06:27 UTC, 4860575 reviewed
最下面那些是添加的wifi客户端显示。不然不显示在线的wifi用户

2020-11-11 06:28 UTC, 4860575 commented on package/lean/autocore/files/arm/index.htm
> + 		<legend><%:Associated Stations%></legend>
wifi的客户端显示。

2020-11-11 08:00 UTC, AmadeusGhost commented on package/lean/autocore/files/arm/index.htm
> + 		<legend><%:Associated Stations%></legend>
那像 r2s 这种没无线的就有问题了 (((

2020-11-13 00:51 UTC, 1715173329 commented
mvebu 的温度是怎么读的？

2020-11-13 11:15 UTC, 4860575 commented
> mvebu 的温度是怎么读的？

root@Gavin:~# awk "BEGIN{printf (\"%.1f\n\",$(cat /sys/class/thermal/thermal_zon
e0/temp)/1000) }"
76.1

2020-11-13 11:54 UTC, 1715173329 commented
project-openwrt/openwrt@633f8c6e59c76d3f9475d299fbc53b983815a977

参考一下这个吧（很抱歉忘记写 reference 了）

2020-11-13 12:52 UTC, 4860575 commented
> [project-openwrt/openwrt@633f8c6](https://github.com/project-openwrt/openwrt/commit/633f8c6e59c76d3f9475d299fbc53b983815a977)
> 
> 参考一下这个吧（很抱歉忘记写 reference 了）

我关掉，你直接pr吧

2020-11-13 12:53 UTC, 4860575 commented
https://github.com/project-openwrt/openwrt/commit/633f8c6e59c76d3f9475d299fbc53b983815a977

2020-11-13 12:54 UTC, closed without merging